apiVersion: v1
kind: Service
metadata:
  name: game-2048-service
spec:
  selector:
    app: 2048-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004
  type: NodePort
